# Generated by Django 3.0.1 on 2019-12-24 13:22

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviewer', '0002_auto_20191224_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('url', models.CharField(max_length=2000, verbose_name='URL')),
                ('state', models.CharField(choices=[('OPENED', 'Opened'), ('MERGED', 'Merged'), ('DECLINED', 'Declined')], default='OPENED', max_length=32, verbose_name='State')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviewer.Reviewer', verbose_name='Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('state', models.CharField(blank=True, choices=[('APPROVED', 'Approved'), ('NEEDS_WORK', 'Needs work')], max_length=32, null=True, verbose_name='State')),
                ('pull_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pull_request.PullRequest', verbose_name='Pull request')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reviewer.Reviewer', verbose_name='Reviewer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='reviewers',
            field=models.ManyToManyField(related_name='reviewing_pull_requests', through='pull_request.Review', to='reviewer.Reviewer'),
        ),
    ]
