# Generated by Django 3.0.1 on 2019-12-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20191224_0858'),
        ('pull_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('pull_request', 'reviewer')},
        ),
    ]
