# Generated by Django 3.0.1 on 2019-12-25 07:38

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_request', '0002_auto_20191224_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('external_id', models.PositiveIntegerField(verbose_name='Pull request external ID')),
                ('author_email', models.EmailField(max_length=254, verbose_name='Author email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pullrequest',
            name='external_id',
            field=models.PositiveIntegerField(default=0, unique=True, verbose_name='External ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NotificationReviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_email', models.EmailField(max_length=254, verbose_name='Reviewer email')),
                ('type', models.CharField(choices=[('ADDED', 'Added'), ('APPROVED', 'Approved'), ('NEEDS_WORK', 'Needs work')], max_length=32, verbose_name='Reviewer type')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pull_request.Notification')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
