# Generated by Django 3.0.1 on 2019-12-25 08:08

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_request', '0003_auto_20191225_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default='http://ya.ru', verbose_name='Pull request URL'),
            preserve_default=False,
        ),
    ]
