# Generated by Django 3.0.1 on 2019-12-25 08:11

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_request', '0004_notification_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='external_id',
            new_name='pull_request_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='url',
            new_name='pull_request_url',
        ),
        migrations.AddField(
            model_name='notification',
            name='pull_request_state',
            field=models.CharField(default='OPEN', max_length=32, verbose_name='Pull request state'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pullrequest',
            name='state',
            field=models.CharField(choices=[('OPEN', 'Opened'), ('MERGED', 'Merged'), ('DECLINED', 'Declined')], max_length=32, verbose_name='State'),
        ),
    ]
