# Generated by Django 3.0.1 on 2019-12-25 08:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('pull_request', '0006_auto_20191225_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='state',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('NEEDS_WORK', 'Needs work')], max_length=32, null=True, verbose_name='State'),
        ),
    ]
