# Generated by Django 3.0.1 on 2019-12-25 09:02

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0002_auto_20191224_0858'),
        ('pull_request', '0007_auto_20191225_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pull_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='pull_request.PullRequest', verbose_name='Pull request'),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='reviewer.Reviewer', verbose_name='Reviewer'),
        ),
    ]
