# Generated by Django 3.0.1 on 2019-12-24 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Telegram username')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='System user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
