# Generated by Django 3.0.1 on 2019-12-24 08:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
